// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * AccountMergeResultCode's original definition in the XDR file is:
 * ```
 * enum AccountMergeResultCode
{
// codes considered as "success" for the operation
ACCOUNT_MERGE_SUCCESS = 0,
// codes considered as "failure" for the operation
ACCOUNT_MERGE_MALFORMED = -1,       // can't merge onto itself
ACCOUNT_MERGE_NO_ACCOUNT = -2,      // destination does not exist
ACCOUNT_MERGE_IMMUTABLE_SET = -3,   // source account has AUTH_IMMUTABLE set
ACCOUNT_MERGE_HAS_SUB_ENTRIES = -4, // account has trust lines/offers
ACCOUNT_MERGE_SEQNUM_TOO_FAR = -5,  // sequence number is over max allowed
ACCOUNT_MERGE_DEST_FULL = -6,       // can't add source balance to
// destination balance
ACCOUNT_MERGE_IS_SPONSOR = -7       // can't merge account that is a sponsor
};
 * ```
 */
enum class AccountMergeResultCode(val value: Int) : XdrElement {
    ACCOUNT_MERGE_SUCCESS(0),
    ACCOUNT_MERGE_MALFORMED(-1),
    ACCOUNT_MERGE_NO_ACCOUNT(-2),
    ACCOUNT_MERGE_IMMUTABLE_SET(-3),
    ACCOUNT_MERGE_HAS_SUB_ENTRIES(-4),
    ACCOUNT_MERGE_SEQNUM_TOO_FAR(-5),
    ACCOUNT_MERGE_DEST_FULL(-6),
    ACCOUNT_MERGE_IS_SPONSOR(-7);

    companion object : XdrElementDecoder<AccountMergeResultCode> {
        override fun decode(stream: XdrInputStream): AccountMergeResultCode {
            return when (val value = stream.readInt()) {
                0 -> ACCOUNT_MERGE_SUCCESS
                -1 -> ACCOUNT_MERGE_MALFORMED
                -2 -> ACCOUNT_MERGE_NO_ACCOUNT
                -3 -> ACCOUNT_MERGE_IMMUTABLE_SET
                -4 -> ACCOUNT_MERGE_HAS_SUB_ENTRIES
                -5 -> ACCOUNT_MERGE_SEQNUM_TOO_FAR
                -6 -> ACCOUNT_MERGE_DEST_FULL
                -7 -> ACCOUNT_MERGE_IS_SPONSOR
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
