// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * AccountEntryExtensionV3's original definition in the XDR file is:
 * ```
 * struct AccountEntryExtensionV3
{
// We can use this to add more fields, or because it is first, to
// change AccountEntryExtensionV3 into a union.
ExtensionPoint ext;

// Ledger number at which `seqNum` took on its present value.
uint32 seqLedger;

// Time at which `seqNum` took on its present value.
TimePoint seqTime;
};
 * ```
 */
data class AccountEntryExtensionV3(
    val ext: ExtensionPoint,
    val seqLedger: Uint32,
    val seqTime: TimePoint,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        ext.encode(stream)
        seqLedger.encode(stream)
        seqTime.encode(stream)
    }

    companion object : XdrElementDecoder<AccountEntryExtensionV3> {
        override fun decode(stream: XdrInputStream): AccountEntryExtensionV3 {
            val ext = ExtensionPoint.decode(stream)
            val seqLedger = me.rahimklaber.stellar.base.xdr.Uint32.decode(stream)
            val seqTime = TimePoint.decode(stream)
            return AccountEntryExtensionV3(
                ext,
                seqLedger,
                seqTime,
            )
        }
    }
}
