// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * AlphaNum4's original definition in the XDR file is:
 * ```
 * struct AlphaNum4
{
AssetCode4 assetCode;
AccountID issuer;
};
 * ```
 */
data class AlphaNum4(
    val assetCode: AssetCode4,
    val issuer: AccountID,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        assetCode.encode(stream)
        issuer.encode(stream)
    }

    companion object : XdrElementDecoder<AlphaNum4> {
        override fun decode(stream: XdrInputStream): AlphaNum4 {
            val assetCode = AssetCode4.decode(stream)
            val issuer = AccountID.decode(stream)
            return AlphaNum4(
                assetCode,
                issuer,
            )
        }
    }
}
