// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * AssetType's original definition in the XDR file is:
 * ```
 * enum AssetType
{
ASSET_TYPE_NATIVE = 0,
ASSET_TYPE_CREDIT_ALPHANUM4 = 1,
ASSET_TYPE_CREDIT_ALPHANUM12 = 2,
ASSET_TYPE_POOL_SHARE = 3
};
 * ```
 */
enum class AssetType(val value: Int) : XdrElement {
    ASSET_TYPE_NATIVE(0),
    ASSET_TYPE_CREDIT_ALPHANUM4(1),
    ASSET_TYPE_CREDIT_ALPHANUM12(2),
    ASSET_TYPE_POOL_SHARE(3);

    companion object : XdrElementDecoder<AssetType> {
        override fun decode(stream: XdrInputStream): AssetType {
            return when (val value = stream.readInt()) {
                0 -> ASSET_TYPE_NATIVE
                1 -> ASSET_TYPE_CREDIT_ALPHANUM4
                2 -> ASSET_TYPE_CREDIT_ALPHANUM12
                3 -> ASSET_TYPE_POOL_SHARE
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
