// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * AuthCert's original definition in the XDR file is:
 * ```
 * struct AuthCert
{
Curve25519Public pubkey;
uint64 expiration;
Signature sig;
};
 * ```
 */
data class AuthCert(
    val pubkey: Curve25519Public,
    val expiration: Uint64,
    val sig: Signature,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        pubkey.encode(stream)
        expiration.encode(stream)
        sig.encode(stream)
    }

    companion object : XdrElementDecoder<AuthCert> {
        override fun decode(stream: XdrInputStream): AuthCert {
            val pubkey = Curve25519Public.decode(stream)
            val expiration = me.rahimklaber.stellar.base.xdr.Uint64.decode(stream)
            val sig = Signature.decode(stream)
            return AuthCert(
                pubkey,
                expiration,
                sig,
            )
        }
    }
}
