// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * BinaryFuseFilterType's original definition in the XDR file is:
 * ```
 * enum BinaryFuseFilterType
{
BINARY_FUSE_FILTER_8_BIT = 0,
BINARY_FUSE_FILTER_16_BIT = 1,
BINARY_FUSE_FILTER_32_BIT = 2
};
 * ```
 */
enum class BinaryFuseFilterType(val value: Int) : XdrElement {
    BINARY_FUSE_FILTER_8_BIT(0),
    BINARY_FUSE_FILTER_16_BIT(1),
    BINARY_FUSE_FILTER_32_BIT(2);

    companion object : XdrElementDecoder<BinaryFuseFilterType> {
        override fun decode(stream: XdrInputStream): BinaryFuseFilterType {
            return when (val value = stream.readInt()) {
                0 -> BINARY_FUSE_FILTER_8_BIT
                1 -> BINARY_FUSE_FILTER_16_BIT
                2 -> BINARY_FUSE_FILTER_32_BIT
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
