// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * BumpSequenceOp's original definition in the XDR file is:
 * ```
 * struct BumpSequenceOp
{
SequenceNumber bumpTo;
};
 * ```
 */
@JvmInline
value class BumpSequenceOp(val bumpTo: SequenceNumber) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        bumpTo.encode(stream)
    }

    companion object : XdrElementDecoder<BumpSequenceOp> {
        override fun decode(stream: XdrInputStream): BumpSequenceOp {
            val bumpTo = SequenceNumber.decode(stream)
            return BumpSequenceOp(
                bumpTo,
            )
        }
    }
}
