// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * ClaimAtomType's original definition in the XDR file is:
 * ```
 * enum ClaimAtomType
{
CLAIM_ATOM_TYPE_V0 = 0,
CLAIM_ATOM_TYPE_ORDER_BOOK = 1,
CLAIM_ATOM_TYPE_LIQUIDITY_POOL = 2
};
 * ```
 */
enum class ClaimAtomType(val value: Int) : XdrElement {
    CLAIM_ATOM_TYPE_V0(0),
    CLAIM_ATOM_TYPE_ORDER_BOOK(1),
    CLAIM_ATOM_TYPE_LIQUIDITY_POOL(2);

    companion object : XdrElementDecoder<ClaimAtomType> {
        override fun decode(stream: XdrInputStream): ClaimAtomType {
            return when (val value = stream.readInt()) {
                0 -> CLAIM_ATOM_TYPE_V0
                1 -> CLAIM_ATOM_TYPE_ORDER_BOOK
                2 -> CLAIM_ATOM_TYPE_LIQUIDITY_POOL
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
