// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * ClaimantType's original definition in the XDR file is:
 * ```
 * enum ClaimantType
{
CLAIMANT_TYPE_V0 = 0
};
 * ```
 */
enum class ClaimantType(val value: Int) : XdrElement {
    CLAIMANT_TYPE_V0(0);

    companion object : XdrElementDecoder<ClaimantType> {
        override fun decode(stream: XdrInputStream): ClaimantType {
            return when (val value = stream.readInt()) {
                0 -> CLAIMANT_TYPE_V0
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
