// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * ColdArchiveArchivedLeaf's original definition in the XDR file is:
 * ```
 * struct ColdArchiveArchivedLeaf
{
uint32 index;
LedgerEntry archivedEntry;
};
 * ```
 */
data class ColdArchiveArchivedLeaf(
    val index: Uint32,
    val archivedEntry: LedgerEntry,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        index.encode(stream)
        archivedEntry.encode(stream)
    }

    companion object : XdrElementDecoder<ColdArchiveArchivedLeaf> {
        override fun decode(stream: XdrInputStream): ColdArchiveArchivedLeaf {
            val index = me.rahimklaber.stellar.base.xdr.Uint32.decode(stream)
            val archivedEntry = LedgerEntry.decode(stream)
            return ColdArchiveArchivedLeaf(
                index,
                archivedEntry,
            )
        }
    }
}
