// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * ConfigSettingSCPTiming's original definition in the XDR file is:
 * ```
 * struct ConfigSettingSCPTiming {
uint32 ledgerTargetCloseTimeMilliseconds;
uint32 nominationTimeoutInitialMilliseconds;
uint32 nominationTimeoutIncrementMilliseconds;
uint32 ballotTimeoutInitialMilliseconds;
uint32 ballotTimeoutIncrementMilliseconds;
};
 * ```
 */
data class ConfigSettingSCPTiming(
    val ledgerTargetCloseTimeMilliseconds: Uint32,
    val nominationTimeoutInitialMilliseconds: Uint32,
    val nominationTimeoutIncrementMilliseconds: Uint32,
    val ballotTimeoutInitialMilliseconds: Uint32,
    val ballotTimeoutIncrementMilliseconds: Uint32,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        ledgerTargetCloseTimeMilliseconds.encode(stream)
        nominationTimeoutInitialMilliseconds.encode(stream)
        nominationTimeoutIncrementMilliseconds.encode(stream)
        ballotTimeoutInitialMilliseconds.encode(stream)
        ballotTimeoutIncrementMilliseconds.encode(stream)
    }

    companion object : XdrElementDecoder<ConfigSettingSCPTiming> {
        override fun decode(stream: XdrInputStream): ConfigSettingSCPTiming {
            val ledgerTargetCloseTimeMilliseconds = Uint32.decode(stream)
            val nominationTimeoutInitialMilliseconds = Uint32.decode(stream)
            val nominationTimeoutIncrementMilliseconds = Uint32.decode(stream)
            val ballotTimeoutInitialMilliseconds = Uint32.decode(stream)
            val ballotTimeoutIncrementMilliseconds = Uint32.decode(stream)
            return ConfigSettingSCPTiming(
                ledgerTargetCloseTimeMilliseconds,
                nominationTimeoutInitialMilliseconds,
                nominationTimeoutIncrementMilliseconds,
                ballotTimeoutInitialMilliseconds,
                ballotTimeoutIncrementMilliseconds,
            )
        }
    }
}
