// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * ConfigSettingContractParallelComputeV0's original definition in the XDR file is:
 * ```
 * struct ConfigSettingContractParallelComputeV0
{
// Maximum number of clusters with dependent transactions allowed in a
// stage of parallel tx set component.
// This effectively sets the lower bound on the number of physical threads
// necessary to effectively apply transaction sets in parallel.
uint32 ledgerMaxDependentTxClusters;
};
 * ```
 */
@JvmInline
value class ConfigSettingContractParallelComputeV0(val ledgerMaxDependentTxClusters: Uint32) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        ledgerMaxDependentTxClusters.encode(stream)
    }

    companion object : XdrElementDecoder<ConfigSettingContractParallelComputeV0> {
        override fun decode(stream: XdrInputStream): ConfigSettingContractParallelComputeV0 {
            val ledgerMaxDependentTxClusters = Uint32.decode(stream)
            return ConfigSettingContractParallelComputeV0(
                ledgerMaxDependentTxClusters,
            )
        }
    }
}
