// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * ConfigSettingContractLedgerCostV0's original definition in the XDR file is:
 * ```
 * struct ConfigSettingContractLedgerCostV0
{
// Maximum number of disk entry read operations per ledger
uint32 ledgerMaxDiskReadEntries;
// Maximum number of bytes of disk reads that can be performed per ledger
uint32 ledgerMaxDiskReadBytes;
// Maximum number of ledger entry write operations per ledger
uint32 ledgerMaxWriteLedgerEntries;
// Maximum number of bytes that can be written per ledger
uint32 ledgerMaxWriteBytes;

// Maximum number of disk entry read operations per transaction
uint32 txMaxDiskReadEntries;
// Maximum number of bytes of disk reads that can be performed per transaction
uint32 txMaxDiskReadBytes;
// Maximum number of ledger entry write operations per transaction
uint32 txMaxWriteLedgerEntries;
// Maximum number of bytes that can be written per transaction
uint32 txMaxWriteBytes;

int64 feeDiskReadLedgerEntry;  // Fee per disk ledger entry read
int64 feeWriteLedgerEntry;     // Fee per ledger entry write

int64 feeDiskRead1KB;          // Fee for reading 1KB disk

// The following parameters determine the write fee per 1KB.
// Rent fee grows linearly until soroban state reaches this size
int64 sorobanStateTargetSizeBytes;
// Fee per 1KB rent when the soroban state is empty
int64 rentFee1KBSorobanStateSizeLow;
// Fee per 1KB rent when the soroban state has reached `sorobanStateTargetSizeBytes`
int64 rentFee1KBSorobanStateSizeHigh;
// Rent fee multiplier for any additional data past the first `sorobanStateTargetSizeBytes`
uint32 sorobanStateRentFeeGrowthFactor;
};
 * ```
 */
data class ConfigSettingContractLedgerCostV0(
    val ledgerMaxDiskReadEntries: Uint32,
    val ledgerMaxDiskReadBytes: Uint32,
    val ledgerMaxWriteLedgerEntries: Uint32,
    val ledgerMaxWriteBytes: Uint32,
    val txMaxDiskReadEntries: Uint32,
    val txMaxDiskReadBytes: Uint32,
    val txMaxWriteLedgerEntries: Uint32,
    val txMaxWriteBytes: Uint32,
    val feeDiskReadLedgerEntry: Int64,
    val feeWriteLedgerEntry: Int64,
    val feeDiskRead1KB: Int64,
    val sorobanStateTargetSizeBytes: Int64,
    val rentFee1KBSorobanStateSizeLow: Int64,
    val rentFee1KBSorobanStateSizeHigh: Int64,
    val sorobanStateRentFeeGrowthFactor: Uint32,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        ledgerMaxDiskReadEntries.encode(stream)
        ledgerMaxDiskReadBytes.encode(stream)
        ledgerMaxWriteLedgerEntries.encode(stream)
        ledgerMaxWriteBytes.encode(stream)
        txMaxDiskReadEntries.encode(stream)
        txMaxDiskReadBytes.encode(stream)
        txMaxWriteLedgerEntries.encode(stream)
        txMaxWriteBytes.encode(stream)
        feeDiskReadLedgerEntry.encode(stream)
        feeWriteLedgerEntry.encode(stream)
        feeDiskRead1KB.encode(stream)
        sorobanStateTargetSizeBytes.encode(stream)
        rentFee1KBSorobanStateSizeLow.encode(stream)
        rentFee1KBSorobanStateSizeHigh.encode(stream)
        sorobanStateRentFeeGrowthFactor.encode(stream)
    }

    companion object : XdrElementDecoder<ConfigSettingContractLedgerCostV0> {
        override fun decode(stream: XdrInputStream): ConfigSettingContractLedgerCostV0 {
            val ledgerMaxDiskReadEntries = Uint32.decode(stream)
            val ledgerMaxDiskReadBytes = Uint32.decode(stream)
            val ledgerMaxWriteLedgerEntries = Uint32.decode(stream)
            val ledgerMaxWriteBytes = Uint32.decode(stream)
            val txMaxDiskReadEntries = Uint32.decode(stream)
            val txMaxDiskReadBytes = Uint32.decode(stream)
            val txMaxWriteLedgerEntries = Uint32.decode(stream)
            val txMaxWriteBytes = Uint32.decode(stream)
            val feeDiskReadLedgerEntry = Int64.decode(stream)
            val feeWriteLedgerEntry = Int64.decode(stream)
            val feeDiskRead1KB = Int64.decode(stream)
            val sorobanStateTargetSizeBytes = Int64.decode(stream)
            val rentFee1KBSorobanStateSizeLow = Int64.decode(stream)
            val rentFee1KBSorobanStateSizeHigh = Int64.decode(stream)
            val sorobanStateRentFeeGrowthFactor = Uint32.decode(stream)
            return ConfigSettingContractLedgerCostV0(
                ledgerMaxDiskReadEntries,
                ledgerMaxDiskReadBytes,
                ledgerMaxWriteLedgerEntries,
                ledgerMaxWriteBytes,
                txMaxDiskReadEntries,
                txMaxDiskReadBytes,
                txMaxWriteLedgerEntries,
                txMaxWriteBytes,
                feeDiskReadLedgerEntry,
                feeWriteLedgerEntry,
                feeDiskRead1KB,
                sorobanStateTargetSizeBytes,
                rentFee1KBSorobanStateSizeLow,
                rentFee1KBSorobanStateSizeHigh,
                sorobanStateRentFeeGrowthFactor,
            )
        }
    }
}
