// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * ConfigSettingContractHistoricalDataV0's original definition in the XDR file is:
 * ```
 * struct ConfigSettingContractHistoricalDataV0
{
int64 feeHistorical1KB; // Fee for storing 1KB in archives
};
 * ```
 */
@JvmInline
value class ConfigSettingContractHistoricalDataV0(val feeHistorical1KB: Int64) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        feeHistorical1KB.encode(stream)
    }

    companion object : XdrElementDecoder<ConfigSettingContractHistoricalDataV0> {
        override fun decode(stream: XdrInputStream): ConfigSettingContractHistoricalDataV0 {
            val feeHistorical1KB = me.rahimklaber.stellar.base.xdr.Int64.decode(stream)
            return ConfigSettingContractHistoricalDataV0(
                feeHistorical1KB,
            )
        }
    }
}
