// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


object Constants {
    val SCSYMBOL_LIMIT = 32
    val CONTRACT_COST_COUNT_LIMIT = 1024
    val SC_SPEC_DOC_LIMIT = 1024
    val MASK_LEDGER_HEADER_FLAGS = 0x7
    val MASK_ACCOUNT_FLAGS = 0x7
    val MASK_ACCOUNT_FLAGS_V17 = 0xF
    val MAX_SIGNERS = 20
    val MASK_TRUSTLINE_FLAGS = 1
    val MASK_TRUSTLINE_FLAGS_V13 = 3
    val MASK_TRUSTLINE_FLAGS_V17 = 7
    val MASK_OFFERENTRY_FLAGS = 1
    val MASK_CLAIMABLE_BALANCE_FLAGS = 0x1
    val AUTH_MSG_FLAG_FLOW_CONTROL_BYTES_REQUESTED = 200
    val TX_ADVERT_VECTOR_MAX_SIZE = 1000
    val TX_DEMAND_VECTOR_MAX_SIZE = 1000
    val MAX_OPS_PER_TX = 100
    val LIQUIDITY_POOL_FEE_V18 = 30
}
