// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * ContractEventType's original definition in the XDR file is:
 * ```
 * enum ContractEventType
{
SYSTEM = 0,
CONTRACT = 1,
DIAGNOSTIC = 2
};
 * ```
 */
enum class ContractEventType(val value: Int) : XdrElement {
    SYSTEM(0),
    CONTRACT(1),
    DIAGNOSTIC(2);

    companion object : XdrElementDecoder<ContractEventType> {
        override fun decode(stream: XdrInputStream): ContractEventType {
            return when (val value = stream.readInt()) {
                0 -> SYSTEM
                1 -> CONTRACT
                2 -> DIAGNOSTIC
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
