// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * ContractDataEntry's original definition in the XDR file is:
 * ```
 * struct ContractDataEntry {
ExtensionPoint ext;

SCAddress contract;
SCVal key;
ContractDataDurability durability;
SCVal val;
};
 * ```
 */
data class ContractDataEntry(
    val ext: ExtensionPoint,
    val contract: SCAddress,
    val key: SCVal,
    val durability: ContractDataDurability,
    val value: SCVal,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        ext.encode(stream)
        contract.encode(stream)
        key.encode(stream)
        durability.encode(stream)
        value.encode(stream)
    }

    companion object : XdrElementDecoder<ContractDataEntry> {
        override fun decode(stream: XdrInputStream): ContractDataEntry {
            val ext = ExtensionPoint.decode(stream)
            val contract = SCAddress.decode(stream)
            val key = SCVal.decode(stream)
            val durability = ContractDataDurability.decode(stream)
            val value = SCVal.decode(stream)
            return ContractDataEntry(
                ext,
                contract,
                key,
                durability,
                value,
            )
        }
    }
}
