// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * Curve25519Public's original definition in the XDR file is:
 * ```
 * struct Curve25519Public
{
opaque key[32];
};
 * ```
 */
@JvmInline
value class Curve25519Public(val key: ByteArray) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        stream.writeBytes(key)
    }

    companion object : XdrElementDecoder<Curve25519Public> {
        override fun decode(stream: XdrInputStream): Curve25519Public {
            val keySize = 32
            val key = stream.readBytes(keySize)
            return Curve25519Public(
                key,
            )
        }
    }
}
