// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * DependentTxCluster's original definition in the XDR file is:
 * ```
 * typedef TransactionEnvelope DependentTxCluster<>;
 * ```
 */
@JvmInline
value class DependentTxCluster(val value: List<TransactionEnvelope>) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        val valueSize = value.size
        stream.writeInt(valueSize)
        value.encodeXdrElements(stream)
    }

    companion object : XdrElementDecoder<DependentTxCluster> {
        override fun decode(stream: XdrInputStream): DependentTxCluster {
            val valueSize = stream.readInt()
            val value: List<TransactionEnvelope> = decodeXdrElementsList(valueSize, stream, TransactionEnvelope.decoder())
            return DependentTxCluster(value)
        }
    }
}
