// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * EndSponsoringFutureReservesResultCode's original definition in the XDR file is:
 * ```
 * enum EndSponsoringFutureReservesResultCode
{
// codes considered as "success" for the operation
END_SPONSORING_FUTURE_RESERVES_SUCCESS = 0,

// codes considered as "failure" for the operation
END_SPONSORING_FUTURE_RESERVES_NOT_SPONSORED = -1
};
 * ```
 */
enum class EndSponsoringFutureReservesResultCode(val value: Int) : XdrElement {
    END_SPONSORING_FUTURE_RESERVES_SUCCESS(0),
    END_SPONSORING_FUTURE_RESERVES_NOT_SPONSORED(-1);

    companion object : XdrElementDecoder<EndSponsoringFutureReservesResultCode> {
        override fun decode(stream: XdrInputStream): EndSponsoringFutureReservesResultCode {
            return when (val value = stream.readInt()) {
                0 -> END_SPONSORING_FUTURE_RESERVES_SUCCESS
                -1 -> END_SPONSORING_FUTURE_RESERVES_NOT_SPONSORED
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
