// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * Error's original definition in the XDR file is:
 * ```
 * struct Error
{
ErrorCode code;
string msg<100>;
};
 * ```
 */
data class Error(
    val code: ErrorCode,
    val msg: String,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        code.encode(stream)
        val msgSize = msg.length
        stream.writeInt(msgSize)
        stream.writeBytes(msg.encodeToByteArray())
    }

    companion object : XdrElementDecoder<Error> {
        override fun decode(stream: XdrInputStream): Error {
            val code = ErrorCode.decode(stream)
            val msgSize = stream.readInt()
            val msg = decodeString(msgSize, stream)
            return Error(
                code,
                msg,
            )
        }
    }
}
