// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * ExtendFootprintTTLResultCode's original definition in the XDR file is:
 * ```
 * enum ExtendFootprintTTLResultCode
{
// codes considered as "success" for the operation
EXTEND_FOOTPRINT_TTL_SUCCESS = 0,

// codes considered as "failure" for the operation
EXTEND_FOOTPRINT_TTL_MALFORMED = -1,
EXTEND_FOOTPRINT_TTL_RESOURCE_LIMIT_EXCEEDED = -2,
EXTEND_FOOTPRINT_TTL_INSUFFICIENT_REFUNDABLE_FEE = -3
};
 * ```
 */
enum class ExtendFootprintTTLResultCode(val value: Int) : XdrElement {
    EXTEND_FOOTPRINT_TTL_SUCCESS(0),
    EXTEND_FOOTPRINT_TTL_MALFORMED(-1),
    EXTEND_FOOTPRINT_TTL_RESOURCE_LIMIT_EXCEEDED(-2),
    EXTEND_FOOTPRINT_TTL_INSUFFICIENT_REFUNDABLE_FEE(-3);

    companion object : XdrElementDecoder<ExtendFootprintTTLResultCode> {
        override fun decode(stream: XdrInputStream): ExtendFootprintTTLResultCode {
            return when (val value = stream.readInt()) {
                0 -> EXTEND_FOOTPRINT_TTL_SUCCESS
                -1 -> EXTEND_FOOTPRINT_TTL_MALFORMED
                -2 -> EXTEND_FOOTPRINT_TTL_RESOURCE_LIMIT_EXCEEDED
                -3 -> EXTEND_FOOTPRINT_TTL_INSUFFICIENT_REFUNDABLE_FEE
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
