// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * FeeBumpTransactionEnvelope's original definition in the XDR file is:
 * ```
 * struct FeeBumpTransactionEnvelope
{
FeeBumpTransaction tx;
/* Each decorated signature is a signature over the SHA256 hash of
 * a TransactionSignaturePayload */
DecoratedSignature signatures<20>;
};
 * ```
 */
data class FeeBumpTransactionEnvelope(
    val tx: FeeBumpTransaction,
    val signatures: List<DecoratedSignature>,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        tx.encode(stream)
        val signaturesSize = signatures.size
        stream.writeInt(signaturesSize)
        signatures.encodeXdrElements(stream)
    }

    companion object : XdrElementDecoder<FeeBumpTransactionEnvelope> {
        override fun decode(stream: XdrInputStream): FeeBumpTransactionEnvelope {
            val tx = FeeBumpTransaction.decode(stream)
            val signaturesSize = stream.readInt()
            val signatures: List<DecoratedSignature> = decodeXdrElementsList(signaturesSize, stream, DecoratedSignature.decoder())
            return FeeBumpTransactionEnvelope(
                tx,
                signatures,
            )
        }
    }
}
