// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * HmacSha256Key's original definition in the XDR file is:
 * ```
 * struct HmacSha256Key
{
opaque key[32];
};
 * ```
 */
@JvmInline
value class HmacSha256Key(val key: ByteArray) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        stream.writeBytes(key)
    }

    companion object : XdrElementDecoder<HmacSha256Key> {
        override fun decode(stream: XdrInputStream): HmacSha256Key {
            val keySize = 32
            val key = stream.readBytes(keySize)
            return HmacSha256Key(
                key,
            )
        }
    }
}
