// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * InflationResultCode's original definition in the XDR file is:
 * ```
 * enum InflationResultCode
{
// codes considered as "success" for the operation
INFLATION_SUCCESS = 0,
// codes considered as "failure" for the operation
INFLATION_NOT_TIME = -1
};
 * ```
 */
enum class InflationResultCode(val value: Int) : XdrElement {
    INFLATION_SUCCESS(0),
    INFLATION_NOT_TIME(-1);

    companion object : XdrElementDecoder<InflationResultCode> {
        override fun decode(stream: XdrInputStream): InflationResultCode {
            return when (val value = stream.readInt()) {
                0 -> INFLATION_SUCCESS
                -1 -> INFLATION_NOT_TIME
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
