// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * Int128Parts's original definition in the XDR file is:
 * ```
 * struct Int128Parts {
int64 hi;
uint64 lo;
};
 * ```
 */
data class Int128Parts(
    val hi: Int64,
    val lo: Uint64,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        hi.encode(stream)
        lo.encode(stream)
    }

    companion object : XdrElementDecoder<Int128Parts> {
        override fun decode(stream: XdrInputStream): Int128Parts {
            val hi = me.rahimklaber.stellar.base.xdr.Int64.decode(stream)
            val lo = me.rahimklaber.stellar.base.xdr.Uint64.decode(stream)
            return Int128Parts(
                hi,
                lo,
            )
        }
    }
}
