// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * Int256Parts's original definition in the XDR file is:
 * ```
 * struct Int256Parts {
int64 hi_hi;
uint64 hi_lo;
uint64 lo_hi;
uint64 lo_lo;
};
 * ```
 */
data class Int256Parts(
    val hiHi: Int64,
    val hiLo: Uint64,
    val loHi: Uint64,
    val loLo: Uint64,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        hiHi.encode(stream)
        hiLo.encode(stream)
        loHi.encode(stream)
        loLo.encode(stream)
    }

    companion object : XdrElementDecoder<Int256Parts> {
        override fun decode(stream: XdrInputStream): Int256Parts {
            val hi_hi = me.rahimklaber.stellar.base.xdr.Int64.decode(stream)
            val hi_lo = me.rahimklaber.stellar.base.xdr.Uint64.decode(stream)
            val lo_hi = me.rahimklaber.stellar.base.xdr.Uint64.decode(stream)
            val lo_lo = me.rahimklaber.stellar.base.xdr.Uint64.decode(stream)
            return Int256Parts(
                hi_hi,
                hi_lo,
                lo_hi,
                lo_lo,
            )
        }
    }
}
