// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * IPAddrType's original definition in the XDR file is:
 * ```
 * enum IPAddrType
{
IPv4 = 0,
IPv6 = 1
};
 * ```
 */
enum class IPAddrType(val value: Int) : XdrElement {
    IPv4(0),
    IPv6(1);

    companion object : XdrElementDecoder<IPAddrType> {
        override fun decode(stream: XdrInputStream): IPAddrType {
            return when (val value = stream.readInt()) {
                0 -> IPv4
                1 -> IPv6
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
