// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * LedgerHeaderFlags's original definition in the XDR file is:
 * ```
 * enum LedgerHeaderFlags
{
DISABLE_LIQUIDITY_POOL_TRADING_FLAG = 0x1,
DISABLE_LIQUIDITY_POOL_DEPOSIT_FLAG = 0x2,
DISABLE_LIQUIDITY_POOL_WITHDRAWAL_FLAG = 0x4
};
 * ```
 */
enum class LedgerHeaderFlags(val value: Int) : XdrElement {
    DISABLE_LIQUIDITY_POOL_TRADING_FLAG(1),
    DISABLE_LIQUIDITY_POOL_DEPOSIT_FLAG(2),
    DISABLE_LIQUIDITY_POOL_WITHDRAWAL_FLAG(4);

    companion object : XdrElementDecoder<LedgerHeaderFlags> {
        override fun decode(stream: XdrInputStream): LedgerHeaderFlags {
            return when (val value = stream.readInt()) {
                1 -> DISABLE_LIQUIDITY_POOL_TRADING_FLAG
                2 -> DISABLE_LIQUIDITY_POOL_DEPOSIT_FLAG
                4 -> DISABLE_LIQUIDITY_POOL_WITHDRAWAL_FLAG
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
