// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * LedgerEntryChangeType's original definition in the XDR file is:
 * ```
 * enum LedgerEntryChangeType
{
LEDGER_ENTRY_CREATED = 0, // entry was added to the ledger
LEDGER_ENTRY_UPDATED = 1, // entry was modified in the ledger
LEDGER_ENTRY_REMOVED = 2, // entry was removed from the ledger
LEDGER_ENTRY_STATE = 3    // value of the entry
};
 * ```
 */
enum class LedgerEntryChangeType(val value: Int) : XdrElement {
    LEDGER_ENTRY_CREATED(0),
    LEDGER_ENTRY_UPDATED(1),
    LEDGER_ENTRY_REMOVED(2),
    LEDGER_ENTRY_STATE(3);

    companion object : XdrElementDecoder<LedgerEntryChangeType> {
        override fun decode(stream: XdrInputStream): LedgerEntryChangeType {
            return when (val value = stream.readInt()) {
                0 -> LEDGER_ENTRY_CREATED
                1 -> LEDGER_ENTRY_UPDATED
                2 -> LEDGER_ENTRY_REMOVED
                3 -> LEDGER_ENTRY_STATE
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
