// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * LedgerCloseMetaV1's original definition in the XDR file is:
 * ```
 * struct LedgerCloseMetaV1
{
LedgerCloseMetaExt ext;

LedgerHeaderHistoryEntry ledgerHeader;

GeneralizedTransactionSet txSet;

// NB: transactions are sorted in apply order here
// fees for all transactions are processed first
// followed by applying transactions
TransactionResultMeta txProcessing<>;

// upgrades are applied last
UpgradeEntryMeta upgradesProcessing<>;

// other misc information attached to the ledger close
SCPHistoryEntry scpInfo<>;

// Size in bytes of live Soroban state, to support downstream
// systems calculating storage fees correctly.
uint64 totalByteSizeOfLiveSorobanState;

// TTL and data/code keys that have been evicted at this ledger.
LedgerKey evictedKeys<>;

// Maintained for backwards compatibility, should never be populated.
LedgerEntry unused<>;
};
 * ```
 */
data class LedgerCloseMetaV1(
    val ext: LedgerCloseMetaExt,
    val ledgerHeader: LedgerHeaderHistoryEntry,
    val txSet: GeneralizedTransactionSet,
    val txProcessing: List<TransactionResultMeta>,
    val upgradesProcessing: List<UpgradeEntryMeta>,
    val scpInfo: List<SCPHistoryEntry>,
    val totalByteSizeOfLiveSorobanState: Uint64,
    val evictedKeys: List<LedgerKey>,
    val unused: List<LedgerEntry>,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        ext.encode(stream)
        ledgerHeader.encode(stream)
        txSet.encode(stream)
        val txProcessingSize = txProcessing.size
        stream.writeInt(txProcessingSize)
        txProcessing.encodeXdrElements(stream)
        val upgradesProcessingSize = upgradesProcessing.size
        stream.writeInt(upgradesProcessingSize)
        upgradesProcessing.encodeXdrElements(stream)
        val scpInfoSize = scpInfo.size
        stream.writeInt(scpInfoSize)
        scpInfo.encodeXdrElements(stream)
        totalByteSizeOfLiveSorobanState.encode(stream)
        val evictedKeysSize = evictedKeys.size
        stream.writeInt(evictedKeysSize)
        evictedKeys.encodeXdrElements(stream)
        val unusedSize = unused.size
        stream.writeInt(unusedSize)
        unused.encodeXdrElements(stream)
    }

    companion object : XdrElementDecoder<LedgerCloseMetaV1> {
        override fun decode(stream: XdrInputStream): LedgerCloseMetaV1 {
            val ext = LedgerCloseMetaExt.decode(stream)
            val ledgerHeader = LedgerHeaderHistoryEntry.decode(stream)
            val txSet = GeneralizedTransactionSet.decode(stream)
            val txProcessingSize = stream.readInt()
            val txProcessing: List<TransactionResultMeta> =
                decodeXdrElementsList(txProcessingSize, stream, TransactionResultMeta.decoder())
            val upgradesProcessingSize = stream.readInt()
            val upgradesProcessing: List<UpgradeEntryMeta> =
                decodeXdrElementsList(upgradesProcessingSize, stream, UpgradeEntryMeta.decoder())
            val scpInfoSize = stream.readInt()
            val scpInfo: List<SCPHistoryEntry> = decodeXdrElementsList(scpInfoSize, stream, SCPHistoryEntry.decoder())
            val totalByteSizeOfLiveSorobanState = Uint64.decode(stream)
            val evictedKeysSize = stream.readInt()
            val evictedKeys: List<LedgerKey> = decodeXdrElementsList(evictedKeysSize, stream, LedgerKey.decoder())
            val unusedSize = stream.readInt()
            val unused: List<LedgerEntry> = decodeXdrElementsList(unusedSize, stream, LedgerEntry.decoder())
            return LedgerCloseMetaV1(
                ext,
                ledgerHeader,
                txSet,
                txProcessing,
                upgradesProcessing,
                scpInfo,
                totalByteSizeOfLiveSorobanState,
                evictedKeys,
                unused,
            )
        }
    }
}
