// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * LedgerSCPMessages's original definition in the XDR file is:
 * ```
 * struct LedgerSCPMessages
{
uint32 ledgerSeq;
SCPEnvelope messages<>;
};
 * ```
 */
data class LedgerSCPMessages(
    val ledgerSeq: Uint32,
    val messages: List<SCPEnvelope>,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        ledgerSeq.encode(stream)
        val messagesSize = messages.size
        stream.writeInt(messagesSize)
        messages.encodeXdrElements(stream)
    }

    companion object : XdrElementDecoder<LedgerSCPMessages> {
        override fun decode(stream: XdrInputStream): LedgerSCPMessages {
            val ledgerSeq = me.rahimklaber.stellar.base.xdr.Uint32.decode(stream)
            val messagesSize = stream.readInt()
            val messages: List<SCPEnvelope> = decodeXdrElementsList(messagesSize, stream, SCPEnvelope.decoder())
            return LedgerSCPMessages(
                ledgerSeq,
                messages,
            )
        }
    }
}
