// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * LedgerEntryType's original definition in the XDR file is:
 * ```
 * enum LedgerEntryType
{
ACCOUNT = 0,
TRUSTLINE = 1,
OFFER = 2,
DATA = 3,
CLAIMABLE_BALANCE = 4,
LIQUIDITY_POOL = 5,
CONTRACT_DATA = 6,
CONTRACT_CODE = 7,
CONFIG_SETTING = 8,
TTL = 9
};
 * ```
 */
enum class LedgerEntryType(val value: Int) : XdrElement {
    ACCOUNT(0),
    TRUSTLINE(1),
    OFFER(2),
    DATA(3),
    CLAIMABLE_BALANCE(4),
    LIQUIDITY_POOL(5),
    CONTRACT_DATA(6),
    CONTRACT_CODE(7),
    CONFIG_SETTING(8),
    TTL(9);

    companion object : XdrElementDecoder<LedgerEntryType> {
        override fun decode(stream: XdrInputStream): LedgerEntryType {
            return when (val value = stream.readInt()) {
                0 -> ACCOUNT
                1 -> TRUSTLINE
                2 -> OFFER
                3 -> DATA
                4 -> CLAIMABLE_BALANCE
                5 -> LIQUIDITY_POOL
                6 -> CONTRACT_DATA
                7 -> CONTRACT_CODE
                8 -> CONFIG_SETTING
                9 -> TTL
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
