// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * Liabilities's original definition in the XDR file is:
 * ```
 * struct Liabilities
{
int64 buying;
int64 selling;
};
 * ```
 */
data class Liabilities(
    val buying: Int64,
    val selling: Int64,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        buying.encode(stream)
        selling.encode(stream)
    }

    companion object : XdrElementDecoder<Liabilities> {
        override fun decode(stream: XdrInputStream): Liabilities {
            val buying = me.rahimklaber.stellar.base.xdr.Int64.decode(stream)
            val selling = me.rahimklaber.stellar.base.xdr.Int64.decode(stream)
            return Liabilities(
                buying,
                selling,
            )
        }
    }
}
