// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * LiquidityPoolType's original definition in the XDR file is:
 * ```
 * enum LiquidityPoolType
{
LIQUIDITY_POOL_CONSTANT_PRODUCT = 0
};
 * ```
 */
enum class LiquidityPoolType(val value: Int) : XdrElement {
    LIQUIDITY_POOL_CONSTANT_PRODUCT(0);

    companion object : XdrElementDecoder<LiquidityPoolType> {
        override fun decode(stream: XdrInputStream): LiquidityPoolType {
            return when (val value = stream.readInt()) {
                0 -> LIQUIDITY_POOL_CONSTANT_PRODUCT
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
