// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * ManageOfferEffect's original definition in the XDR file is:
 * ```
 * enum ManageOfferEffect
{
MANAGE_OFFER_CREATED = 0,
MANAGE_OFFER_UPDATED = 1,
MANAGE_OFFER_DELETED = 2
};
 * ```
 */
enum class ManageOfferEffect(val value: Int) : XdrElement {
    MANAGE_OFFER_CREATED(0),
    MANAGE_OFFER_UPDATED(1),
    MANAGE_OFFER_DELETED(2);

    companion object : XdrElementDecoder<ManageOfferEffect> {
        override fun decode(stream: XdrInputStream): ManageOfferEffect {
            return when (val value = stream.readInt()) {
                0 -> MANAGE_OFFER_CREATED
                1 -> MANAGE_OFFER_UPDATED
                2 -> MANAGE_OFFER_DELETED
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
