// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * ManageBuyOfferResult's original definition in the XDR file is:
 * ```
 * union ManageBuyOfferResult switch (ManageBuyOfferResultCode code)
{
case MANAGE_BUY_OFFER_SUCCESS:
ManageOfferSuccessResult success;
case MANAGE_BUY_OFFER_MALFORMED:
case MANAGE_BUY_OFFER_SELL_NO_TRUST:
case MANAGE_BUY_OFFER_BUY_NO_TRUST:
case MANAGE_BUY_OFFER_SELL_NOT_AUTHORIZED:
case MANAGE_BUY_OFFER_BUY_NOT_AUTHORIZED:
case MANAGE_BUY_OFFER_LINE_FULL:
case MANAGE_BUY_OFFER_UNDERFUNDED:
case MANAGE_BUY_OFFER_CROSS_SELF:
case MANAGE_BUY_OFFER_SELL_NO_ISSUER:
case MANAGE_BUY_OFFER_BUY_NO_ISSUER:
case MANAGE_BUY_OFFER_NOT_FOUND:
case MANAGE_BUY_OFFER_LOW_RESERVE:
void;
};
 * ```
 */
sealed class ManageBuyOfferResult(val type: ManageBuyOfferResultCode) : XdrElement {
    fun successOrNull(): ManageBuyOfferSuccess? = if (this is ManageBuyOfferSuccess) this else null
    data class ManageBuyOfferSuccess(
        val success: ManageOfferSuccessResult,
    ) : ManageBuyOfferResult(ManageBuyOfferResultCode.MANAGE_BUY_OFFER_SUCCESS) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
            success.encode(stream)
        }
    }

    data object ManageBuyOfferMalformed : ManageBuyOfferResult(ManageBuyOfferResultCode.MANAGE_BUY_OFFER_MALFORMED) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object ManageBuyOfferSellNoTrust : ManageBuyOfferResult(ManageBuyOfferResultCode.MANAGE_BUY_OFFER_SELL_NO_TRUST) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object ManageBuyOfferBuyNoTrust : ManageBuyOfferResult(ManageBuyOfferResultCode.MANAGE_BUY_OFFER_BUY_NO_TRUST) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object ManageBuyOfferSellNotAuthorized : ManageBuyOfferResult(ManageBuyOfferResultCode.MANAGE_BUY_OFFER_SELL_NOT_AUTHORIZED) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object ManageBuyOfferBuyNotAuthorized : ManageBuyOfferResult(ManageBuyOfferResultCode.MANAGE_BUY_OFFER_BUY_NOT_AUTHORIZED) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object ManageBuyOfferLineFull : ManageBuyOfferResult(ManageBuyOfferResultCode.MANAGE_BUY_OFFER_LINE_FULL) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object ManageBuyOfferUnderfunded : ManageBuyOfferResult(ManageBuyOfferResultCode.MANAGE_BUY_OFFER_UNDERFUNDED) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object ManageBuyOfferCrossSelf : ManageBuyOfferResult(ManageBuyOfferResultCode.MANAGE_BUY_OFFER_CROSS_SELF) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object ManageBuyOfferSellNoIssuer : ManageBuyOfferResult(ManageBuyOfferResultCode.MANAGE_BUY_OFFER_SELL_NO_ISSUER) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object ManageBuyOfferBuyNoIssuer : ManageBuyOfferResult(ManageBuyOfferResultCode.MANAGE_BUY_OFFER_BUY_NO_ISSUER) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object ManageBuyOfferNotFound : ManageBuyOfferResult(ManageBuyOfferResultCode.MANAGE_BUY_OFFER_NOT_FOUND) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object ManageBuyOfferLowReserve : ManageBuyOfferResult(ManageBuyOfferResultCode.MANAGE_BUY_OFFER_LOW_RESERVE) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    companion object : XdrElementDecoder<ManageBuyOfferResult> {
        override fun decode(stream: XdrInputStream): ManageBuyOfferResult {
            return when (val type = ManageBuyOfferResultCode.decode(stream)) {
                ManageBuyOfferResultCode.MANAGE_BUY_OFFER_SUCCESS -> {
                    val success = ManageOfferSuccessResult.decode(stream)
                    ManageBuyOfferSuccess(success)
                }

                ManageBuyOfferResultCode.MANAGE_BUY_OFFER_MALFORMED -> ManageBuyOfferMalformed
                ManageBuyOfferResultCode.MANAGE_BUY_OFFER_SELL_NO_TRUST -> ManageBuyOfferSellNoTrust
                ManageBuyOfferResultCode.MANAGE_BUY_OFFER_BUY_NO_TRUST -> ManageBuyOfferBuyNoTrust
                ManageBuyOfferResultCode.MANAGE_BUY_OFFER_SELL_NOT_AUTHORIZED -> ManageBuyOfferSellNotAuthorized
                ManageBuyOfferResultCode.MANAGE_BUY_OFFER_BUY_NOT_AUTHORIZED -> ManageBuyOfferBuyNotAuthorized
                ManageBuyOfferResultCode.MANAGE_BUY_OFFER_LINE_FULL -> ManageBuyOfferLineFull
                ManageBuyOfferResultCode.MANAGE_BUY_OFFER_UNDERFUNDED -> ManageBuyOfferUnderfunded
                ManageBuyOfferResultCode.MANAGE_BUY_OFFER_CROSS_SELF -> ManageBuyOfferCrossSelf
                ManageBuyOfferResultCode.MANAGE_BUY_OFFER_SELL_NO_ISSUER -> ManageBuyOfferSellNoIssuer
                ManageBuyOfferResultCode.MANAGE_BUY_OFFER_BUY_NO_ISSUER -> ManageBuyOfferBuyNoIssuer
                ManageBuyOfferResultCode.MANAGE_BUY_OFFER_NOT_FOUND -> ManageBuyOfferNotFound
                ManageBuyOfferResultCode.MANAGE_BUY_OFFER_LOW_RESERVE -> ManageBuyOfferLowReserve
                else -> throw IllegalArgumentException("unknown type: $type")
            }
        }
    }
}
