// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * MuxedEd25519Account's original definition in the XDR file is:
 * ```
 * struct MuxedEd25519Account
{
uint64 id;
uint256 ed25519;
};
 * ```
 */
data class MuxedEd25519Account(
    val id: Uint64,
    val ed25519: Uint256,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        id.encode(stream)
        ed25519.encode(stream)
    }

    companion object : XdrElementDecoder<MuxedEd25519Account> {
        override fun decode(stream: XdrInputStream): MuxedEd25519Account {
            val id = me.rahimklaber.stellar.base.xdr.Uint64.decode(stream)
            val ed25519 = Uint256.decode(stream)
            return MuxedEd25519Account(
                id,
                ed25519,
            )
        }
    }
}
