// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * OperationMeta's original definition in the XDR file is:
 * ```
 * struct OperationMeta
{
LedgerEntryChanges changes;
};
 * ```
 */
@JvmInline
value class OperationMeta(val changes: LedgerEntryChanges) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        changes.encode(stream)
    }

    companion object : XdrElementDecoder<OperationMeta> {
        override fun decode(stream: XdrInputStream): OperationMeta {
            val changes = LedgerEntryChanges.decode(stream)
            return OperationMeta(
                changes,
            )
        }
    }
}
