// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * OperationType's original definition in the XDR file is:
 * ```
 * enum OperationType
{
CREATE_ACCOUNT = 0,
PAYMENT = 1,
PATH_PAYMENT_STRICT_RECEIVE = 2,
MANAGE_SELL_OFFER = 3,
CREATE_PASSIVE_SELL_OFFER = 4,
SET_OPTIONS = 5,
CHANGE_TRUST = 6,
ALLOW_TRUST = 7,
ACCOUNT_MERGE = 8,
INFLATION = 9,
MANAGE_DATA = 10,
BUMP_SEQUENCE = 11,
MANAGE_BUY_OFFER = 12,
PATH_PAYMENT_STRICT_SEND = 13,
CREATE_CLAIMABLE_BALANCE = 14,
CLAIM_CLAIMABLE_BALANCE = 15,
BEGIN_SPONSORING_FUTURE_RESERVES = 16,
END_SPONSORING_FUTURE_RESERVES = 17,
REVOKE_SPONSORSHIP = 18,
CLAWBACK = 19,
CLAWBACK_CLAIMABLE_BALANCE = 20,
SET_TRUST_LINE_FLAGS = 21,
LIQUIDITY_POOL_DEPOSIT = 22,
LIQUIDITY_POOL_WITHDRAW = 23,
INVOKE_HOST_FUNCTION = 24,
EXTEND_FOOTPRINT_TTL = 25,
RESTORE_FOOTPRINT = 26
};
 * ```
 */
enum class OperationType(val value: Int) : XdrElement {
    CREATE_ACCOUNT(0),
    PAYMENT(1),
    PATH_PAYMENT_STRICT_RECEIVE(2),
    MANAGE_SELL_OFFER(3),
    CREATE_PASSIVE_SELL_OFFER(4),
    SET_OPTIONS(5),
    CHANGE_TRUST(6),
    ALLOW_TRUST(7),
    ACCOUNT_MERGE(8),
    INFLATION(9),
    MANAGE_DATA(10),
    BUMP_SEQUENCE(11),
    MANAGE_BUY_OFFER(12),
    PATH_PAYMENT_STRICT_SEND(13),
    CREATE_CLAIMABLE_BALANCE(14),
    CLAIM_CLAIMABLE_BALANCE(15),
    BEGIN_SPONSORING_FUTURE_RESERVES(16),
    END_SPONSORING_FUTURE_RESERVES(17),
    REVOKE_SPONSORSHIP(18),
    CLAWBACK(19),
    CLAWBACK_CLAIMABLE_BALANCE(20),
    SET_TRUST_LINE_FLAGS(21),
    LIQUIDITY_POOL_DEPOSIT(22),
    LIQUIDITY_POOL_WITHDRAW(23),
    INVOKE_HOST_FUNCTION(24),
    EXTEND_FOOTPRINT_TTL(25),
    RESTORE_FOOTPRINT(26);

    companion object : XdrElementDecoder<OperationType> {
        override fun decode(stream: XdrInputStream): OperationType {
            return when (val value = stream.readInt()) {
                0 -> CREATE_ACCOUNT
                1 -> PAYMENT
                2 -> PATH_PAYMENT_STRICT_RECEIVE
                3 -> MANAGE_SELL_OFFER
                4 -> CREATE_PASSIVE_SELL_OFFER
                5 -> SET_OPTIONS
                6 -> CHANGE_TRUST
                7 -> ALLOW_TRUST
                8 -> ACCOUNT_MERGE
                9 -> INFLATION
                10 -> MANAGE_DATA
                11 -> BUMP_SEQUENCE
                12 -> MANAGE_BUY_OFFER
                13 -> PATH_PAYMENT_STRICT_SEND
                14 -> CREATE_CLAIMABLE_BALANCE
                15 -> CLAIM_CLAIMABLE_BALANCE
                16 -> BEGIN_SPONSORING_FUTURE_RESERVES
                17 -> END_SPONSORING_FUTURE_RESERVES
                18 -> REVOKE_SPONSORSHIP
                19 -> CLAWBACK
                20 -> CLAWBACK_CLAIMABLE_BALANCE
                21 -> SET_TRUST_LINE_FLAGS
                22 -> LIQUIDITY_POOL_DEPOSIT
                23 -> LIQUIDITY_POOL_WITHDRAW
                24 -> INVOKE_HOST_FUNCTION
                25 -> EXTEND_FOOTPRINT_TTL
                26 -> RESTORE_FOOTPRINT
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
