// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * ParallelTxsComponent's original definition in the XDR file is:
 * ```
 * struct ParallelTxsComponent
{
int64* baseFee;
// A sequence of stages that *may* have arbitrary data dependencies between
// each other, i.e. in a general case the stage execution order may not be
// arbitrarily shuffled without affecting the end result.
ParallelTxExecutionStage executionStages<>;
};
 * ```
 */
data class ParallelTxsComponent(
    val baseFee: Int64?,
    val executionStages: List<ParallelTxExecutionStage>,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        if (baseFee != null) {
            stream.writeInt(1)
            baseFee.encode(stream)
        } else {
            stream.writeInt(0)
        }
        val executionStagesSize = executionStages.size
        stream.writeInt(executionStagesSize)
        executionStages.encodeXdrElements(stream)
    }

    companion object : XdrElementDecoder<ParallelTxsComponent> {
        override fun decode(stream: XdrInputStream): ParallelTxsComponent {
            val baseFeePresent = stream.readInt()
            val baseFee = if (baseFeePresent != 0) {
                Int64.decode(stream)
            } else {
                null
            }
            val executionStagesSize = stream.readInt()
            val executionStages: List<ParallelTxExecutionStage> =
                decodeXdrElementsList(executionStagesSize, stream, ParallelTxExecutionStage.decoder())
            return ParallelTxsComponent(
                baseFee,
                executionStages,
            )
        }
    }
}
