// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * ParallelTxExecutionStage's original definition in the XDR file is:
 * ```
 * typedef DependentTxCluster ParallelTxExecutionStage<>;
 * ```
 */
@JvmInline
value class ParallelTxExecutionStage(val value: List<DependentTxCluster>) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        val valueSize = value.size
        stream.writeInt(valueSize)
        value.encodeXdrElements(stream)
    }

    companion object : XdrElementDecoder<ParallelTxExecutionStage> {
        override fun decode(stream: XdrInputStream): ParallelTxExecutionStage {
            val valueSize = stream.readInt()
            val value: List<DependentTxCluster> = decodeXdrElementsList(valueSize, stream, DependentTxCluster.decoder())
            return ParallelTxExecutionStage(value)
        }
    }
}
