// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * PersistedSCPStateV1's original definition in the XDR file is:
 * ```
 * struct PersistedSCPStateV1
{
// Tx sets are saved separately
SCPEnvelope scpEnvelopes<>;
SCPQuorumSet quorumSets<>;
};
 * ```
 */
data class PersistedSCPStateV1(
    val scpEnvelopes: List<SCPEnvelope>,
    val quorumSets: List<SCPQuorumSet>,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        val scpEnvelopesSize = scpEnvelopes.size
        stream.writeInt(scpEnvelopesSize)
        scpEnvelopes.encodeXdrElements(stream)
        val quorumSetsSize = quorumSets.size
        stream.writeInt(quorumSetsSize)
        quorumSets.encodeXdrElements(stream)
    }

    companion object : XdrElementDecoder<PersistedSCPStateV1> {
        override fun decode(stream: XdrInputStream): PersistedSCPStateV1 {
            val scpEnvelopesSize = stream.readInt()
            val scpEnvelopes: List<SCPEnvelope> = decodeXdrElementsList(scpEnvelopesSize, stream, SCPEnvelope.decoder())
            val quorumSetsSize = stream.readInt()
            val quorumSets: List<SCPQuorumSet> = decodeXdrElementsList(quorumSetsSize, stream, SCPQuorumSet.decoder())
            return PersistedSCPStateV1(
                scpEnvelopes,
                quorumSets,
            )
        }
    }
}
