// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * RestoreFootprintResultCode's original definition in the XDR file is:
 * ```
 * enum RestoreFootprintResultCode
{
// codes considered as "success" for the operation
RESTORE_FOOTPRINT_SUCCESS = 0,

// codes considered as "failure" for the operation
RESTORE_FOOTPRINT_MALFORMED = -1,
RESTORE_FOOTPRINT_RESOURCE_LIMIT_EXCEEDED = -2,
RESTORE_FOOTPRINT_INSUFFICIENT_REFUNDABLE_FEE = -3
};
 * ```
 */
enum class RestoreFootprintResultCode(val value: Int) : XdrElement {
    RESTORE_FOOTPRINT_SUCCESS(0),
    RESTORE_FOOTPRINT_MALFORMED(-1),
    RESTORE_FOOTPRINT_RESOURCE_LIMIT_EXCEEDED(-2),
    RESTORE_FOOTPRINT_INSUFFICIENT_REFUNDABLE_FEE(-3);

    companion object : XdrElementDecoder<RestoreFootprintResultCode> {
        override fun decode(stream: XdrInputStream): RestoreFootprintResultCode {
            return when (val value = stream.readInt()) {
                0 -> RESTORE_FOOTPRINT_SUCCESS
                -1 -> RESTORE_FOOTPRINT_MALFORMED
                -2 -> RESTORE_FOOTPRINT_RESOURCE_LIMIT_EXCEEDED
                -3 -> RESTORE_FOOTPRINT_INSUFFICIENT_REFUNDABLE_FEE
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
