// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * RevokeSponsorshipResultCode's original definition in the XDR file is:
 * ```
 * enum RevokeSponsorshipResultCode
{
// codes considered as "success" for the operation
REVOKE_SPONSORSHIP_SUCCESS = 0,

// codes considered as "failure" for the operation
REVOKE_SPONSORSHIP_DOES_NOT_EXIST = -1,
REVOKE_SPONSORSHIP_NOT_SPONSOR = -2,
REVOKE_SPONSORSHIP_LOW_RESERVE = -3,
REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE = -4,
REVOKE_SPONSORSHIP_MALFORMED = -5
};
 * ```
 */
enum class RevokeSponsorshipResultCode(val value: Int) : XdrElement {
    REVOKE_SPONSORSHIP_SUCCESS(0),
    REVOKE_SPONSORSHIP_DOES_NOT_EXIST(-1),
    REVOKE_SPONSORSHIP_NOT_SPONSOR(-2),
    REVOKE_SPONSORSHIP_LOW_RESERVE(-3),
    REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE(-4),
    REVOKE_SPONSORSHIP_MALFORMED(-5);

    companion object : XdrElementDecoder<RevokeSponsorshipResultCode> {
        override fun decode(stream: XdrInputStream): RevokeSponsorshipResultCode {
            return when (val value = stream.readInt()) {
                0 -> REVOKE_SPONSORSHIP_SUCCESS
                -1 -> REVOKE_SPONSORSHIP_DOES_NOT_EXIST
                -2 -> REVOKE_SPONSORSHIP_NOT_SPONSOR
                -3 -> REVOKE_SPONSORSHIP_LOW_RESERVE
                -4 -> REVOKE_SPONSORSHIP_ONLY_TRANSFERABLE
                -5 -> REVOKE_SPONSORSHIP_MALFORMED
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
