// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * SCBytes's original definition in the XDR file is:
 * ```
 * typedef opaque SCBytes<>;
 * ```
 */
@JvmInline
value class SCBytes(val value: ByteArray) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        val valueSize = value.size
        stream.writeInt(valueSize)
        stream.writeBytes(value)
    }

    companion object : XdrElementDecoder<SCBytes> {
        override fun decode(stream: XdrInputStream): SCBytes {
            val valueSize = stream.readInt()
            val value = stream.readBytes(valueSize)
            return SCBytes(value)
        }
    }
}
