// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * SCMap's original definition in the XDR file is:
 * ```
 * typedef SCMapEntry SCMap<>;
 * ```
 */
@JvmInline
value class SCMap(val value: List<SCMapEntry>) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        val valueSize = value.size
        stream.writeInt(valueSize)
        value.encodeXdrElements(stream)
    }

    companion object : XdrElementDecoder<SCMap> {
        override fun decode(stream: XdrInputStream): SCMap {
            val valueSize = stream.readInt()
            val value: List<SCMapEntry> = decodeXdrElementsList(valueSize, stream, SCMapEntry.decoder())
            return SCMap(value)
        }
    }
}
