// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * SCMetaKind's original definition in the XDR file is:
 * ```
 * enum SCMetaKind
{
SC_META_V0 = 0
};
 * ```
 */
enum class SCMetaKind(val value: Int) : XdrElement {
    SC_META_V0(0);

    companion object : XdrElementDecoder<SCMetaKind> {
        override fun decode(stream: XdrInputStream): SCMetaKind {
            val value = stream.readInt()
            return when (value) {
                0 -> SC_META_V0
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
