// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * SCNonceKey's original definition in the XDR file is:
 * ```
 * struct SCNonceKey {
int64 nonce;
};
 * ```
 */
@JvmInline
value class SCNonceKey(val nonce: Int64) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        nonce.encode(stream)
    }

    companion object : XdrElementDecoder<SCNonceKey> {
        override fun decode(stream: XdrInputStream): SCNonceKey {
            val nonce = me.rahimklaber.stellar.base.xdr.Int64.decode(stream)
            return SCNonceKey(
                nonce,
            )
        }
    }
}
