// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * SCPHistoryEntryV0's original definition in the XDR file is:
 * ```
 * struct SCPHistoryEntryV0
{
SCPQuorumSet quorumSets<>; // additional quorum sets used by ledgerMessages
LedgerSCPMessages ledgerMessages;
};
 * ```
 */
data class SCPHistoryEntryV0(
    val quorumSets: List<SCPQuorumSet>,
    val ledgerMessages: LedgerSCPMessages,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        val quorumSetsSize = quorumSets.size
        stream.writeInt(quorumSetsSize)
        quorumSets.encodeXdrElements(stream)
        ledgerMessages.encode(stream)
    }

    companion object : XdrElementDecoder<SCPHistoryEntryV0> {
        override fun decode(stream: XdrInputStream): SCPHistoryEntryV0 {
            val quorumSetsSize = stream.readInt()
            val quorumSets: List<SCPQuorumSet> = decodeXdrElementsList(quorumSetsSize, stream, SCPQuorumSet.decoder())
            val ledgerMessages = LedgerSCPMessages.decode(stream)
            return SCPHistoryEntryV0(
                quorumSets,
                ledgerMessages,
            )
        }
    }
}
