// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * SCSpecUDTUnionCaseVoidV0's original definition in the XDR file is:
 * ```
 * struct SCSpecUDTUnionCaseVoidV0
{
string doc<SC_SPEC_DOC_LIMIT>;
string name<60>;
};
 * ```
 */
data class SCSpecUDTUnionCaseVoidV0(
    val doc: String,
    val name: String,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        val docSize = doc.length
        stream.writeInt(docSize)
        stream.writeBytes(doc.encodeToByteArray())
        val nameSize = name.length
        stream.writeInt(nameSize)
        stream.writeBytes(name.encodeToByteArray())
    }

    companion object : XdrElementDecoder<SCSpecUDTUnionCaseVoidV0> {
        override fun decode(stream: XdrInputStream): SCSpecUDTUnionCaseVoidV0 {
            val docSize = stream.readInt()
            val doc = decodeString(docSize, stream)
            val nameSize = stream.readInt()
            val name = decodeString(nameSize, stream)
            return SCSpecUDTUnionCaseVoidV0(
                doc,
                name,
            )
        }
    }
}
