// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * SCSpecEventDataFormat's original definition in the XDR file is:
 * ```
 * enum SCSpecEventDataFormat
{
SC_SPEC_EVENT_DATA_FORMAT_SINGLE_VALUE = 0,
SC_SPEC_EVENT_DATA_FORMAT_VEC = 1,
SC_SPEC_EVENT_DATA_FORMAT_MAP = 2
};
 * ```
 */
enum class SCSpecEventDataFormat(val value: Int) : XdrElement {
    SC_SPEC_EVENT_DATA_FORMAT_SINGLE_VALUE(0),
    SC_SPEC_EVENT_DATA_FORMAT_VEC(1),
    SC_SPEC_EVENT_DATA_FORMAT_MAP(2);

    companion object : XdrElementDecoder<SCSpecEventDataFormat> {
        override fun decode(stream: XdrInputStream): SCSpecEventDataFormat {
            return when (val value = stream.readInt()) {
                0 -> SC_SPEC_EVENT_DATA_FORMAT_SINGLE_VALUE
                1 -> SC_SPEC_EVENT_DATA_FORMAT_VEC
                2 -> SC_SPEC_EVENT_DATA_FORMAT_MAP
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
