// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * SCSpecTypeResult's original definition in the XDR file is:
 * ```
 * struct SCSpecTypeResult
{
SCSpecTypeDef okType;
SCSpecTypeDef errorType;
};
 * ```
 */
data class SCSpecTypeResult(
    val okType: SCSpecTypeDef,
    val errorType: SCSpecTypeDef,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        okType.encode(stream)
        errorType.encode(stream)
    }

    companion object : XdrElementDecoder<SCSpecTypeResult> {
        override fun decode(stream: XdrInputStream): SCSpecTypeResult {
            val okType = SCSpecTypeDef.decode(stream)
            val errorType = SCSpecTypeDef.decode(stream)
            return SCSpecTypeResult(
                okType,
                errorType,
            )
        }
    }
}
