// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * SCSpecTypeVec's original definition in the XDR file is:
 * ```
 * struct SCSpecTypeVec
{
SCSpecTypeDef elementType;
};
 * ```
 */
@JvmInline
value class SCSpecTypeVec(val elementType: SCSpecTypeDef) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        elementType.encode(stream)
    }

    companion object : XdrElementDecoder<SCSpecTypeVec> {
        override fun decode(stream: XdrInputStream): SCSpecTypeVec {
            val elementType = SCSpecTypeDef.decode(stream)
            return SCSpecTypeVec(
                elementType,
            )
        }
    }
}
