// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * SCString's original definition in the XDR file is:
 * ```
 * typedef string SCString<>;
 * ```
 */
@JvmInline
value class SCString(val value: String) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        val valueSize = value.length
        stream.writeInt(valueSize)
        stream.writeBytes(value.encodeToByteArray())
    }

    companion object : XdrElementDecoder<SCString> {
        override fun decode(stream: XdrInputStream): SCString {
            val valueSize = stream.readInt()
            val value = decodeString(valueSize, stream)
            return SCString(value)
        }
    }
}
