// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * SetTrustLineFlagsResult's original definition in the XDR file is:
 * ```
 * union SetTrustLineFlagsResult switch (SetTrustLineFlagsResultCode code)
{
case SET_TRUST_LINE_FLAGS_SUCCESS:
void;
case SET_TRUST_LINE_FLAGS_MALFORMED:
case SET_TRUST_LINE_FLAGS_NO_TRUST_LINE:
case SET_TRUST_LINE_FLAGS_CANT_REVOKE:
case SET_TRUST_LINE_FLAGS_INVALID_STATE:
case SET_TRUST_LINE_FLAGS_LOW_RESERVE:
void;
};
 * ```
 */
sealed class SetTrustLineFlagsResult(val type: SetTrustLineFlagsResultCode) : XdrElement {
    data object SetTrustLineFlagsSuccess : SetTrustLineFlagsResult(SetTrustLineFlagsResultCode.SET_TRUST_LINE_FLAGS_SUCCESS) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object SetTrustLineFlagsMalformed : SetTrustLineFlagsResult(SetTrustLineFlagsResultCode.SET_TRUST_LINE_FLAGS_MALFORMED) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object SetTrustLineFlagsNoTrustLine : SetTrustLineFlagsResult(SetTrustLineFlagsResultCode.SET_TRUST_LINE_FLAGS_NO_TRUST_LINE) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object SetTrustLineFlagsCantRevoke : SetTrustLineFlagsResult(SetTrustLineFlagsResultCode.SET_TRUST_LINE_FLAGS_CANT_REVOKE) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object SetTrustLineFlagsInvalidState : SetTrustLineFlagsResult(SetTrustLineFlagsResultCode.SET_TRUST_LINE_FLAGS_INVALID_STATE) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    data object SetTrustLineFlagsLowReserve : SetTrustLineFlagsResult(SetTrustLineFlagsResultCode.SET_TRUST_LINE_FLAGS_LOW_RESERVE) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    companion object : XdrElementDecoder<SetTrustLineFlagsResult> {
        override fun decode(stream: XdrInputStream): SetTrustLineFlagsResult {
            return when (val type = SetTrustLineFlagsResultCode.decode(stream)) {
                SetTrustLineFlagsResultCode.SET_TRUST_LINE_FLAGS_SUCCESS -> SetTrustLineFlagsSuccess
                SetTrustLineFlagsResultCode.SET_TRUST_LINE_FLAGS_MALFORMED -> SetTrustLineFlagsMalformed
                SetTrustLineFlagsResultCode.SET_TRUST_LINE_FLAGS_NO_TRUST_LINE -> SetTrustLineFlagsNoTrustLine
                SetTrustLineFlagsResultCode.SET_TRUST_LINE_FLAGS_CANT_REVOKE -> SetTrustLineFlagsCantRevoke
                SetTrustLineFlagsResultCode.SET_TRUST_LINE_FLAGS_INVALID_STATE -> SetTrustLineFlagsInvalidState
                SetTrustLineFlagsResultCode.SET_TRUST_LINE_FLAGS_LOW_RESERVE -> SetTrustLineFlagsLowReserve
                else -> throw IllegalArgumentException("unknown type: $type")
            }
        }
    }
}
