// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * ShortHashSeed's original definition in the XDR file is:
 * ```
 * struct ShortHashSeed
{
opaque seed[16];
};
 * ```
 */
@JvmInline
value class ShortHashSeed(val seed: ByteArray) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        stream.writeBytes(seed)
    }

    companion object : XdrElementDecoder<ShortHashSeed> {
        override fun decode(stream: XdrInputStream): ShortHashSeed {
            val seedSize = 16
            val seed = stream.readBytes(seedSize)
            return ShortHashSeed(
                seed,
            )
        }
    }
}
