// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * SignedTimeSlicedSurveyStartCollectingMessage's original definition in the XDR file is:
 * ```
 * struct SignedTimeSlicedSurveyStartCollectingMessage
{
Signature signature;
TimeSlicedSurveyStartCollectingMessage startCollecting;
};
 * ```
 */
data class SignedTimeSlicedSurveyStartCollectingMessage(
    val signature: Signature,
    val startCollecting: TimeSlicedSurveyStartCollectingMessage,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        signature.encode(stream)
        startCollecting.encode(stream)
    }

    companion object : XdrElementDecoder<SignedTimeSlicedSurveyStartCollectingMessage> {
        override fun decode(stream: XdrInputStream): SignedTimeSlicedSurveyStartCollectingMessage {
            val signature = Signature.decode(stream)
            val startCollecting = TimeSlicedSurveyStartCollectingMessage.decode(stream)
            return SignedTimeSlicedSurveyStartCollectingMessage(
                signature,
                startCollecting,
            )
        }
    }
}
