// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * Signature's original definition in the XDR file is:
 * ```
 * typedef opaque Signature<64>;
 * ```
 */
@JvmInline
value class Signature(val value: ByteArray) : XdrElement {
    init {
        require(value.size <= 64) {
            "Invalid length for Signature"
        }
    }

    override fun encode(stream: XdrOutputStream) {
        val valueSize = value.size
        stream.writeInt(valueSize)
        stream.writeBytes(value)
    }

    companion object : XdrElementDecoder<Signature> {
        override fun decode(stream: XdrInputStream): Signature {
            val valueSize = stream.readInt()
            val value = stream.readBytes(valueSize)
            return Signature(value)
        }
    }
}
