// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * SignedTimeSlicedSurveyStopCollectingMessage's original definition in the XDR file is:
 * ```
 * struct SignedTimeSlicedSurveyStopCollectingMessage
{
Signature signature;
TimeSlicedSurveyStopCollectingMessage stopCollecting;
};
 * ```
 */
data class SignedTimeSlicedSurveyStopCollectingMessage(
    val signature: Signature,
    val stopCollecting: TimeSlicedSurveyStopCollectingMessage,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        signature.encode(stream)
        stopCollecting.encode(stream)
    }

    companion object : XdrElementDecoder<SignedTimeSlicedSurveyStopCollectingMessage> {
        override fun decode(stream: XdrInputStream): SignedTimeSlicedSurveyStopCollectingMessage {
            val signature = Signature.decode(stream)
            val stopCollecting = TimeSlicedSurveyStopCollectingMessage.decode(stream)
            return SignedTimeSlicedSurveyStopCollectingMessage(
                signature,
                stopCollecting,
            )
        }
    }
}
