// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * SimplePaymentResult's original definition in the XDR file is:
 * ```
 * struct SimplePaymentResult
{
AccountID destination;
Asset asset;
int64 amount;
};
 * ```
 */
data class SimplePaymentResult(
    val destination: AccountID,
    val asset: Asset,
    val amount: Int64,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        destination.encode(stream)
        asset.encode(stream)
        amount.encode(stream)
    }

    companion object : XdrElementDecoder<SimplePaymentResult> {
        override fun decode(stream: XdrInputStream): SimplePaymentResult {
            val destination = AccountID.decode(stream)
            val asset = Asset.decode(stream)
            val amount = me.rahimklaber.stellar.base.xdr.Int64.decode(stream)
            return SimplePaymentResult(
                destination,
                asset,
                amount,
            )
        }
    }
}
