// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * SorobanTransactionMetaExt's original definition in the XDR file is:
 * ```
 * union SorobanTransactionMetaExt switch (int v)
{
case 0:
void;
case 1:
SorobanTransactionMetaExtV1 v1;
};
 * ```
 */
sealed class SorobanTransactionMetaExt(val type: Int) : XdrElement {
    data object SorobanTransactionMetaExtV0 : SorobanTransactionMetaExt(0) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
        }
    }

    fun v1OrNull(): SorobanTransactionMetaExtV1? = if (this is SorobanTransactionMetaExtV1) this else null
    data class SorobanTransactionMetaExtV1(
        val v1: me.rahimklaber.stellar.base.xdr.SorobanTransactionMetaExtV1,
    ) : SorobanTransactionMetaExt(1) {
        override fun encode(stream: XdrOutputStream) {
            type.encode(stream)
            v1.encode(stream)
        }
    }

    companion object : XdrElementDecoder<SorobanTransactionMetaExt> {
        override fun decode(stream: XdrInputStream): SorobanTransactionMetaExt {
            return when (val type = Int.decode(stream)) {
                0 -> SorobanTransactionMetaExtV0
                1 -> {
                    val v1 = me.rahimklaber.stellar.base.xdr.SorobanTransactionMetaExtV1.decode(stream)
                    SorobanTransactionMetaExtV1(v1)
                }

                else -> throw IllegalArgumentException("unknown type: $type")
            }
        }
    }
}
