// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * SorobanAddressCredentials's original definition in the XDR file is:
 * ```
 * struct SorobanAddressCredentials
{
SCAddress address;
int64 nonce;
uint32 signatureExpirationLedger;
SCVal signature;
};
 * ```
 */
data class SorobanAddressCredentials(
    val address: SCAddress,
    val nonce: Int64,
    val signatureExpirationLedger: Uint32,
    val signature: SCVal,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        address.encode(stream)
        nonce.encode(stream)
        signatureExpirationLedger.encode(stream)
        signature.encode(stream)
    }

    companion object : XdrElementDecoder<SorobanAddressCredentials> {
        override fun decode(stream: XdrInputStream): SorobanAddressCredentials {
            val address = SCAddress.decode(stream)
            val nonce = me.rahimklaber.stellar.base.xdr.Int64.decode(stream)
            val signatureExpirationLedger = me.rahimklaber.stellar.base.xdr.Uint32.decode(stream)
            val signature = SCVal.decode(stream)
            return SorobanAddressCredentials(
                address,
                nonce,
                signatureExpirationLedger,
                signature,
            )
        }
    }
}
