// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * SorobanCredentialsType's original definition in the XDR file is:
 * ```
 * enum SorobanCredentialsType
{
SOROBAN_CREDENTIALS_SOURCE_ACCOUNT = 0,
SOROBAN_CREDENTIALS_ADDRESS = 1,
SOROBAN_CREDENTIALS_ADDRESS_V2 = 2,
SOROBAN_CREDENTIALS_ADDRESS_WITH_DELEGATES = 3
};
* ```
*/
enum class SorobanCredentialsType(val value: Int) : XdrElement {
   SOROBAN_CREDENTIALS_SOURCE_ACCOUNT(0),
   SOROBAN_CREDENTIALS_ADDRESS(1),
   SOROBAN_CREDENTIALS_ADDRESS_V2(2),
   SOROBAN_CREDENTIALS_ADDRESS_WITH_DELEGATES(3);

   companion object : XdrElementDecoder<SorobanCredentialsType> {
       override fun decode(stream: XdrInputStream): SorobanCredentialsType {
           return when (val value = stream.readInt()) {
               0 -> SOROBAN_CREDENTIALS_SOURCE_ACCOUNT
               1 -> SOROBAN_CREDENTIALS_ADDRESS
               2 -> SOROBAN_CREDENTIALS_ADDRESS_V2
               3 -> SOROBAN_CREDENTIALS_ADDRESS_WITH_DELEGATES
               else -> throw IllegalArgumentException("Unknown enum value: " + value)
           }
       }
   }

   override fun encode(stream: XdrOutputStream) {
       stream.writeInt(value)
   }
}
