// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * SponsorshipDescriptor's original definition in the XDR file is:
 * ```
 * typedef AccountID* SponsorshipDescriptor;
 * ```
 */
@JvmInline
value class SponsorshipDescriptor(val value: AccountID?) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        if (value != null) {
            stream.writeInt(1)
            value.encode(stream)
        } else {
            stream.writeInt(0)
        }
    }

    companion object : XdrElementDecoder<SponsorshipDescriptor> {
        override fun decode(stream: XdrInputStream): SponsorshipDescriptor {
            val valuePresent = stream.readInt()
            val value = if (valuePresent != 0) {
                AccountID.decode(stream)
            } else {
                null
            }
            return SponsorshipDescriptor(value)
        }
    }
}
