// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * StellarValueType's original definition in the XDR file is:
 * ```
 * enum StellarValueType
{
STELLAR_VALUE_BASIC = 0,
STELLAR_VALUE_SIGNED = 1
};
 * ```
 */
enum class StellarValueType(val value: Int) : XdrElement {
    STELLAR_VALUE_BASIC(0),
    STELLAR_VALUE_SIGNED(1);

    companion object : XdrElementDecoder<StellarValueType> {
        override fun decode(stream: XdrInputStream): StellarValueType {
            return when (val value = stream.readInt()) {
                0 -> STELLAR_VALUE_BASIC
                1 -> STELLAR_VALUE_SIGNED
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
