// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * String64's original definition in the XDR file is:
 * ```
 * typedef string string64<64>;
 * ```
 */
@JvmInline
value class String64(val value: String) : XdrElement {
    init {
        require(value.length <= 64) {
            "Invalid length for String64"
        }
    }

    override fun encode(stream: XdrOutputStream) {
        val valueSize = value.length
        stream.writeInt(valueSize)
        stream.writeBytes(value.encodeToByteArray())
    }

    companion object : XdrElementDecoder<String64> {
        override fun decode(stream: XdrInputStream): String64 {
            val valueSize = stream.readInt()
            val value = decodeString(valueSize, stream)
            return String64(value)
        }
    }
}
