// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * SurveyMessageResponseType's original definition in the XDR file is:
 * ```
 * enum SurveyMessageResponseType
{
SURVEY_TOPOLOGY_RESPONSE_V2 = 2
};
 * ```
 */
enum class SurveyMessageResponseType(val value: Int) : XdrElement {
    SURVEY_TOPOLOGY_RESPONSE_V2(2);

    companion object : XdrElementDecoder<SurveyMessageResponseType> {
        override fun decode(stream: XdrInputStream): SurveyMessageResponseType {
            return when (val value = stream.readInt()) {
                2 -> SURVEY_TOPOLOGY_RESPONSE_V2
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
