// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * Thresholds's original definition in the XDR file is:
 * ```
 * typedef opaque Thresholds[4];
 * ```
 */
@JvmInline
value class Thresholds(val value: ByteArray) : XdrElement {
    init {
        require(value.size == 4) {
            "Invalid length for Thresholds"
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeBytes(value)
    }

    companion object : XdrElementDecoder<Thresholds> {
        override fun decode(stream: XdrInputStream): Thresholds {
            val valueSize = 4
            val value = stream.readBytes(valueSize)
            return Thresholds(value)
        }
    }
}
