// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * TimeSlicedPeerDataList's original definition in the XDR file is:
 * ```
 * typedef TimeSlicedPeerData TimeSlicedPeerDataList<25>;
 * ```
 */
@JvmInline
value class TimeSlicedPeerDataList(val value: List<TimeSlicedPeerData>) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        val valueSize = value.size
        stream.writeInt(valueSize)
        value.encodeXdrElements(stream)
    }

    companion object : XdrElementDecoder<TimeSlicedPeerDataList> {
        override fun decode(stream: XdrInputStream): TimeSlicedPeerDataList {
            val valueSize = stream.readInt()
            val value: List<TimeSlicedPeerData> = decodeXdrElementsList(valueSize, stream, TimeSlicedPeerData.decoder())
            return TimeSlicedPeerDataList(value)
        }
    }
}
