// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * TimePoint's original definition in the XDR file is:
 * ```
 * typedef uint64 TimePoint;
 * ```
 */
@JvmInline
value class TimePoint(val value: Uint64) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        value.encode(stream)
    }

    companion object : XdrElementDecoder<TimePoint> {
        override fun decode(stream: XdrInputStream): TimePoint {
            val value = me.rahimklaber.stellar.base.xdr.Uint64.decode(stream)
            return TimePoint(value)
        }
    }
}
