// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * TimeSlicedSurveyRequestMessage's original definition in the XDR file is:
 * ```
 * struct TimeSlicedSurveyRequestMessage
{
SurveyRequestMessage request;
uint32 nonce;
uint32 inboundPeersIndex;
uint32 outboundPeersIndex;
};
 * ```
 */
data class TimeSlicedSurveyRequestMessage(
    val request: SurveyRequestMessage,
    val nonce: Uint32,
    val inboundPeersIndex: Uint32,
    val outboundPeersIndex: Uint32,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        request.encode(stream)
        nonce.encode(stream)
        inboundPeersIndex.encode(stream)
        outboundPeersIndex.encode(stream)
    }

    companion object : XdrElementDecoder<TimeSlicedSurveyRequestMessage> {
        override fun decode(stream: XdrInputStream): TimeSlicedSurveyRequestMessage {
            val request = SurveyRequestMessage.decode(stream)
            val nonce = me.rahimklaber.stellar.base.xdr.Uint32.decode(stream)
            val inboundPeersIndex = me.rahimklaber.stellar.base.xdr.Uint32.decode(stream)
            val outboundPeersIndex = me.rahimklaber.stellar.base.xdr.Uint32.decode(stream)
            return TimeSlicedSurveyRequestMessage(
                request,
                nonce,
                inboundPeersIndex,
                outboundPeersIndex,
            )
        }
    }
}
