// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * TimeSlicedSurveyStartCollectingMessage's original definition in the XDR file is:
 * ```
 * struct TimeSlicedSurveyStartCollectingMessage
{
NodeID surveyorID;
uint32 nonce;
uint32 ledgerNum;
};
 * ```
 */
data class TimeSlicedSurveyStartCollectingMessage(
    val surveyorID: NodeID,
    val nonce: Uint32,
    val ledgerNum: Uint32,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        surveyorID.encode(stream)
        nonce.encode(stream)
        ledgerNum.encode(stream)
    }

    companion object : XdrElementDecoder<TimeSlicedSurveyStartCollectingMessage> {
        override fun decode(stream: XdrInputStream): TimeSlicedSurveyStartCollectingMessage {
            val surveyorID = NodeID.decode(stream)
            val nonce = me.rahimklaber.stellar.base.xdr.Uint32.decode(stream)
            val ledgerNum = me.rahimklaber.stellar.base.xdr.Uint32.decode(stream)
            return TimeSlicedSurveyStartCollectingMessage(
                surveyorID,
                nonce,
                ledgerNum,
            )
        }
    }
}
