// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * TransactionMetaV1's original definition in the XDR file is:
 * ```
 * struct TransactionMetaV1
{
LedgerEntryChanges txChanges; // tx level changes if any
OperationMeta operations<>;   // meta for each operation
};
 * ```
 */
data class TransactionMetaV1(
    val txChanges: LedgerEntryChanges,
    val operations: List<OperationMeta>,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        txChanges.encode(stream)
        val operationsSize = operations.size
        stream.writeInt(operationsSize)
        operations.encodeXdrElements(stream)
    }

    companion object : XdrElementDecoder<TransactionMetaV1> {
        override fun decode(stream: XdrInputStream): TransactionMetaV1 {
            val txChanges = LedgerEntryChanges.decode(stream)
            val operationsSize = stream.readInt()
            val operations: List<OperationMeta> = decodeXdrElementsList(operationsSize, stream, OperationMeta.decoder())
            return TransactionMetaV1(
                txChanges,
                operations,
            )
        }
    }
}
