// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * TransactionResultPair's original definition in the XDR file is:
 * ```
 * struct TransactionResultPair
{
Hash transactionHash;
TransactionResult result; // result for the transaction
};
 * ```
 */
data class TransactionResultPair(
    val transactionHash: Hash,
    val result: TransactionResult,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        transactionHash.encode(stream)
        result.encode(stream)
    }

    companion object : XdrElementDecoder<TransactionResultPair> {
        override fun decode(stream: XdrInputStream): TransactionResultPair {
            val transactionHash = Hash.decode(stream)
            val result = TransactionResult.decode(stream)
            return TransactionResultPair(
                transactionHash,
                result,
            )
        }
    }
}
