// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * TransactionEventStage's original definition in the XDR file is:
 * ```
 * enum TransactionEventStage {
// The event has happened before any one of the transactions has its
// operations applied.
TRANSACTION_EVENT_STAGE_BEFORE_ALL_TXS = 0,
// The event has happened immediately after operations of the transaction
// have been applied.
TRANSACTION_EVENT_STAGE_AFTER_TX = 1,
// The event has happened after every transaction had its operations
// applied.
TRANSACTION_EVENT_STAGE_AFTER_ALL_TXS = 2
};
 * ```
 */
enum class TransactionEventStage(val value: Int) : XdrElement {
    TRANSACTION_EVENT_STAGE_BEFORE_ALL_TXS(0),
    TRANSACTION_EVENT_STAGE_AFTER_TX(1),
    TRANSACTION_EVENT_STAGE_AFTER_ALL_TXS(2);

    companion object : XdrElementDecoder<TransactionEventStage> {
        override fun decode(stream: XdrInputStream): TransactionEventStage {
            return when (val value = stream.readInt()) {
                0 -> TRANSACTION_EVENT_STAGE_BEFORE_ALL_TXS
                1 -> TRANSACTION_EVENT_STAGE_AFTER_TX
                2 -> TRANSACTION_EVENT_STAGE_AFTER_ALL_TXS
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
