// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * TransactionResultMeta's original definition in the XDR file is:
 * ```
 * struct TransactionResultMeta
{
TransactionResultPair result;
LedgerEntryChanges feeProcessing;
TransactionMeta txApplyProcessing;
};
 * ```
 */
data class TransactionResultMeta(
    val result: TransactionResultPair,
    val feeProcessing: LedgerEntryChanges,
    val txApplyProcessing: TransactionMeta,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        result.encode(stream)
        feeProcessing.encode(stream)
        txApplyProcessing.encode(stream)
    }

    companion object : XdrElementDecoder<TransactionResultMeta> {
        override fun decode(stream: XdrInputStream): TransactionResultMeta {
            val result = TransactionResultPair.decode(stream)
            val feeProcessing = LedgerEntryChanges.decode(stream)
            val txApplyProcessing = TransactionMeta.decode(stream)
            return TransactionResultMeta(
                result,
                feeProcessing,
                txApplyProcessing,
            )
        }
    }
}
