// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * TransactionEvent's original definition in the XDR file is:
 * ```
 * struct TransactionEvent {
TransactionEventStage stage;  // Stage at which an event has occurred.
ContractEvent event;  // The contract event that has occurred.
};
 * ```
 */
data class TransactionEvent(
    val stage: TransactionEventStage,
    val event: ContractEvent,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        stage.encode(stream)
        event.encode(stream)
    }

    companion object : XdrElementDecoder<TransactionEvent> {
        override fun decode(stream: XdrInputStream): TransactionEvent {
            val stage = TransactionEventStage.decode(stream)
            val event = ContractEvent.decode(stream)
            return TransactionEvent(
                stage,
                event,
            )
        }
    }
}
