// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * TTLEntry's original definition in the XDR file is:
 * ```
 * struct TTLEntry {
// Hash of the LedgerKey that is associated with this TTLEntry
Hash keyHash;
uint32 liveUntilLedgerSeq;
};
 * ```
 */
data class TTLEntry(
    val keyHash: Hash,
    val liveUntilLedgerSeq: Uint32,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        keyHash.encode(stream)
        liveUntilLedgerSeq.encode(stream)
    }

    companion object : XdrElementDecoder<TTLEntry> {
        override fun decode(stream: XdrInputStream): TTLEntry {
            val keyHash = Hash.decode(stream)
            val liveUntilLedgerSeq = me.rahimklaber.stellar.base.xdr.Uint32.decode(stream)
            return TTLEntry(
                keyHash,
                liveUntilLedgerSeq,
            )
        }
    }
}
