// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * TxAdvertVector's original definition in the XDR file is:
 * ```
 * typedef Hash TxAdvertVector<TX_ADVERT_VECTOR_MAX_SIZE>;
 * ```
 */
@JvmInline
value class TxAdvertVector(val value: List<Hash>) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        val valueSize = value.size
        stream.writeInt(valueSize)
        value.encodeXdrElements(stream)
    }

    companion object : XdrElementDecoder<TxAdvertVector> {
        override fun decode(stream: XdrInputStream): TxAdvertVector {
            val valueSize = stream.readInt()
            val value: List<Hash> = decodeXdrElementsList(valueSize, stream, Hash.decoder())
            return TxAdvertVector(value)
        }
    }
}
