// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr

import kotlin.jvm.JvmInline


/**
 * TxDemandVector's original definition in the XDR file is:
 * ```
 * typedef Hash TxDemandVector<TX_DEMAND_VECTOR_MAX_SIZE>;
 * ```
 */
@JvmInline
value class TxDemandVector(val value: List<Hash>) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        val valueSize = value.size
        stream.writeInt(valueSize)
        value.encodeXdrElements(stream)
    }

    companion object : XdrElementDecoder<TxDemandVector> {
        override fun decode(stream: XdrInputStream): TxDemandVector {
            val valueSize = stream.readInt()
            val value: List<Hash> = decodeXdrElementsList(valueSize, stream, Hash.decoder())
            return TxDemandVector(value)
        }
    }
}
