// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * TxSetComponentType's original definition in the XDR file is:
 * ```
 * enum TxSetComponentType
{
// txs with effective fee <= bid derived from a base fee (if any).
// If base fee is not specified, no discount is applied.
TXSET_COMP_TXS_MAYBE_DISCOUNTED_FEE = 0
};
 * ```
 */
enum class TxSetComponentType(val value: Int) : XdrElement {
    TXSET_COMP_TXS_MAYBE_DISCOUNTED_FEE(0);

    companion object : XdrElementDecoder<TxSetComponentType> {
        override fun decode(stream: XdrInputStream): TxSetComponentType {
            return when (val value = stream.readInt()) {
                0 -> TXSET_COMP_TXS_MAYBE_DISCOUNTED_FEE
                else -> throw IllegalArgumentException("Unknown enum value: " + value)
            }
        }
    }

    override fun encode(stream: XdrOutputStream) {
        stream.writeInt(value)
    }
}
