// Automatically generated by xdrgen
// DO NOT EDIT or your changes may be overwritten

package me.rahimklaber.stellar.base.xdr


/**
 * UInt128Parts's original definition in the XDR file is:
 * ```
 * struct UInt128Parts {
uint64 hi;
uint64 lo;
};
 * ```
 */
data class UInt128Parts(
    val hi: Uint64,
    val lo: Uint64,
) : XdrElement {
    override fun encode(stream: XdrOutputStream) {
        hi.encode(stream)
        lo.encode(stream)
    }

    companion object : XdrElementDecoder<UInt128Parts> {
        override fun decode(stream: XdrInputStream): UInt128Parts {
            val hi = me.rahimklaber.stellar.base.xdr.Uint64.decode(stream)
            val lo = me.rahimklaber.stellar.base.xdr.Uint64.decode(stream)
            return UInt128Parts(
                hi,
                lo,
            )
        }
    }
}
